apiVersion: v1
appVersion: "1.31"
description: SemanticMediaWiki
name: semanticmediawiki
version: 0.1.0
home: https://github.com/wirehead/wirehead-charts/tree/master/charts/semanticmediawiki
icon: https://raw.githubusercontent.com/wirehead/semantic-mediawiki-docker/master/icons/favicon-202x202.png
keywords:
- mediawiki
- semanticmediawiki
- smw
- wiki
- http
- web
- application
- php
sources:
- https://github.com/wirehead/semantic-mediawiki-docker
engine: gotpl
